// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOtyXglJji7rma6OfrCF7Fnc9ITk8uI1U',
    appId: '1:1031931096220:web:615840729d6e1b4d7c1159',
    messagingSenderId: '1031931096220',
    projectId: 'eventsphere-42550',
    authDomain: 'eventsphere-42550.firebaseapp.com',
    storageBucket: 'eventsphere-42550.appspot.com',
    measurementId: 'G-3J62TSXE3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQ_E4aZBQreT8IoutBiFj9qfr7wkMuzw',
    appId: '1:1031931096220:android:3731b78a632adff27c1159',
    messagingSenderId: '1031931096220',
    projectId: 'eventsphere-42550',
    storageBucket: 'eventsphere-42550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxPDj-qAzPCqSnGqI3NDVhe2z2FYVSKc',
    appId: '1:1031931096220:ios:10d594596dd2cd657c1159',
    messagingSenderId: '1031931096220',
    projectId: 'eventsphere-42550',
    storageBucket: 'eventsphere-42550.appspot.com',
    iosBundleId: 'com.example.eventsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZxPDj-qAzPCqSnGqI3NDVhe2z2FYVSKc',
    appId: '1:1031931096220:ios:820431ac172020ed7c1159',
    messagingSenderId: '1031931096220',
    projectId: 'eventsphere-42550',
    storageBucket: 'eventsphere-42550.appspot.com',
    iosBundleId: 'com.example.eventsphere.RunnerTests',
  );
}
